<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thailand_agreeterms</name>
   <tag></tag>
   <elementGuidId>3bd6a3e0-3c4c-4409-bd71-2b5780cb51eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agree-to-terms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agree-to-terms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf80708f-1f3e-49be-9ea9-f721f609f607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>944d1df9-d027-4f85-b15c-2db9e6f2f7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg-check-box</value>
      <webElementGuid>5cd96667-0d1d-429c-949d-3f9de57cad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agree-to-terms</value>
      <webElementGuid>862e655d-b320-4f35-ad07-5570422d4ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agreeterms</value>
      <webElementGuid>6dcc0ad5-ffbb-485f-be45-cdf3a83bd6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agree-to-terms&quot;)</value>
      <webElementGuid>a84cf0a3-455c-416d-88eb-e1514af9922d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agree-to-terms']</value>
      <webElementGuid>a0ec34a3-6218-4b38-bf85-73a01c7c729a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='agreetermsid']/input</value>
      <webElementGuid>ab0b912b-2846-4735-b19d-ccf95ba2c3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>cea5eb95-7f6e-4650-ac6f-ba48fed4bbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'agree-to-terms' and @name = 'agreeterms']</value>
      <webElementGuid>c25f9fd9-53cd-4f40-968f-e09507b7a7e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
