<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_iusername</name>
   <tag></tag>
   <elementGuidId>ec53d4dd-48bd-411d-91e8-5931683aafd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkUsername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkUsername</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>916ba025-d27a-4ae9-982d-1bd1dfa2dbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6547cc3-e432-4b16-8295-ec276a55509d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showToolip</value>
      <webElementGuid>ccad72ad-aab2-4008-8616-db32d35d7df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Minimum 3 Characters and only contain numbers, letters, underscores and maximum 1 dot</value>
      <webElementGuid>d48a2f21-361c-4412-9334-431f3cadff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iusername</value>
      <webElementGuid>aa6a4d16-0cd3-426b-a90c-eef7d84f6890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkUsername</value>
      <webElementGuid>0a643ce9-0e3f-4222-b9cf-7c3c7798eff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1bf45027-eefe-4c7b-aacc-5e0c4b8361ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkUsername&quot;)</value>
      <webElementGuid>3ab6bd30-9812-4888-85bc-0dc59c46d7da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkUsername']</value>
      <webElementGuid>5d743d38-13cd-4f51-9bbf-dc2f65dba12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='regForm']/div[10]/input</value>
      <webElementGuid>fb9c20c3-2ac5-4c9b-80d4-e39cadfcf2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>6e6f6a1d-bd2a-4f01-8570-352a844c4dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Minimum 3 Characters and only contain numbers, letters, underscores and maximum 1 dot' and @name = 'iusername' and @id = 'checkUsername']</value>
      <webElementGuid>a0c4b76e-f7d4-4d98-89c5-8ecabb880095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
